# Language; English: en, 简体普通话: cmn_Hans, 简体文言文: lzh_Hans
lang: §{lang, en}

# Will not display the death screen
auto_respawn: §{auto_respawn, true}
# Set to true to auto back to the place of death after the player dies
auto_back: §{auto_back, false}

# Back to the random ground near the place of death
back_random:
  enable: §{back_random.enable, true}
  # Must > 0
  min: §{back_random.min, 8}
  # Must > min
  max: §{back_random.max, 32}
  # The maximum number of try to generate a random location
  # Must >= 10
  max_try: §{back_random.max_try, 100}
  # The number of times a player can retry after a failure
  # Must >= 1
  max_retry: §{back_random.max_retry, 3}
  # Generate uniformly random location
  uniform: §{back_random.uniform, true}
  # Generate random location on land as much as possible
  try_to_land: §{back_random.try_to_land, true}
  # Never generate random location in the water
  never_water: §{back_random.never_water, false}
  # Try generate under the tree
  try_not_leaves: §{back_random.try_not_leaves, true}

# Use /back to back at any time
back_command: §{back_command, true}
# show 'you can use /back' message
# require {back_command:true}
show_back_command_msg: §{show_back_command_msg, false}
# Will not display the respawn GUI
# require {back_command: true}
no_gui: §{no_gui, false}

# Show death location
show_death_loc: §{show_death_loc, false}

# Store the location of the death
store_location: §{store_location, true}

# Use /killself to kill self
kill_self_command: §{kill_self_command, true}