name: HomeOrBack
version: 1.1.0
author: meowtype.io
main: io.meowtype.homeorback.HomeOrBack
permissions:
  homeorback.*:
    default: false
    children:
      homeorback.op: true
      homeorback.base: true
  homeorback.op:
    default: op
  homeorback.base:
    default: true
    children:
      homeorback.back: true
      homeorback.killself: true
  homeorback.base.back:
    default: true
  homeorback.base.killself:
    default: true
commands:
  homeorback:
    aliases:
    - hob
    - HomeOrBack
    - home-or-back
    permission: homeorback.base
  homeorback-back:
    aliases:
    - back
    permission: homeorback.base.back
  homeorback-killself:
    aliases:
    - killself
    - ks
    - kills
    permission: homeorback.base.killself