name: HomeOrBack
version: 1.1.0
author: meowtype.io
main: io.meowtype.homeorback.HomeOrBack
permissions:
  hob.*:
    default: true
    children:
      hob.back: true
      hob.op: true
  hob.op:
    default: op
  hob.back:
    default: true
commands:
  hob:
    aliases:
    - HomeOrBack
    - home-or-back
    permission: hob.*
  back:
    permission: hob.back